require("rj.plugins.auto-save")
-- require("rj.plugins.catppuccin")

-- All the mini plugins
require("rj.plugins.mini-statusline")
require("rj.plugins.mini-notify")
require("rj.plugins.mini-pairs")
require("rj.plugins.mini-files")
require("rj.plugins.mini-icons")
require("rj.plugins.mini-color")
require("rj.plugins.mini-comment")
require("rj.plugins.mini-git")
require("rj.plugins.mini-indentscope")
-- require("rj.plugins.mini-completion")
require("rj.plugins.mini-cursorword")
require("rj.plugins.mini-hipatterns")
require("rj.plugins.mini-surround")

require("rj.plugins.gitsigns")
require("rj.plugins.hop")
require("rj.plugins.nvim-telescope")
require("rj.plugins.project")
require("rj.plugins.conform")
require("rj.plugins.cybu")
require("rj.plugins.jaq")
require("rj.plugins.barbecue")
require("rj.plugins.nvim-treesitter")
require("rj.plugins.nvim-ts-autotag")
require("rj.plugins.mason")
require("rj.plugins.harpoon")
require("rj.plugins.swenv")
require("rj.plugins.autocomplete")
require("rj.plugins.toggleterm")
-- require("rj.plugins.care")
require("rj.plugins.blink")
require("rj.plugins.leetcode")
