Later(function()
  Add({
    source = "nvim-telescope/telescope.nvim",
    depends = { "nvim-lua/plenary.nvim" },
  })
  local telescope = require("telescope")
  local actions = require("telescope.actions")
  local border = {
    prompt = { "─", "│", " ", "│", "┌", "┐", "│", "│" },
    results = { "─", "│", "─", "│", "├", "┤", "┘", "└" },
    preview = { "─", "│", "─", "│", "┌", "┐", "┘", "└" },
  }
  telescope.setup({
    defaults = {
      initial_mode = "normal",
      prompt_prefix = " ",
      selection_caret = " ",
      path_display = { "smart" },
      border = true,
      borderchars = { "─", "│", "─", "│", "┌", "┐", "┘", "└" },
      file_ignore_patterns = {
        ".git/",
        "target/",
        "docs/",
        "vendor/*",
        "%.lock",
        "__pycache__/*",
        "%.sqlite3",
        "%.ipynb",
        "node_modules/*",
        "%.jpg",
        "%.jpeg",
        "%.png",
        "%.svg",
        "%.otf",
        "%.ttf",
        "%.webp",
        ".dart_tool/",
        ".github/",
        ".gradle/",
        ".idea/",
        ".settings/",
        ".vscode/",
        "__pycache__/",
        "build/",
        "env/",
        "gradle/",
        "node_modules/",
        "%.pdb",
        "%.dll",
        "%.class",
        "%.exe",
        "%.cache",
        "%.ico",
        "%.pdf",
        "%.dylib",
        "%.jar",
        "%.docx",
        "%.met",
        "smalljre_*/*",
        ".vale/",
        "%.burp",
        "%.mp4",
        "%.mkv",
        "%.rar",
        "%.zip",
        "%.7z",
        "%.tar",
        "%.bz2",
        "%.epub",
        "%.flac",
        "%.tar.gz",
      },
      mappings = {
        i = {
          ["<C-n>"] = actions.cycle_history_next,
          ["<C-p>"] = actions.cycle_history_prev,
          ["<C-j>"] = actions.move_selection_next,
          ["<C-k>"] = actions.move_selection_previous,
          ["<C-b>"] = actions.results_scrolling_up,
          ["<C-f>"] = actions.results_scrolling_down,
          ["<C-c>"] = actions.close,
          ["<Down>"] = actions.move_selection_next,
          ["<Up>"] = actions.move_selection_previous,
          ["<CR>"] = actions.select_default,
          ["<C-s>"] = actions.select_horizontal,
          ["<C-v>"] = actions.select_vertical,
          ["<C-t>"] = actions.select_tab,
          ["<c-d>"] = actions.delete_buffer,
          -- ["<C-u>"] = actions.preview_scrolling_up,
          -- ["<C-d>"] = actions.preview_scrolling_down,

          -- ["<Tab>"] = actions.toggle_selection + actions.move_selection_worse,
          ["<Tab>"] = actions.close,
          ["<S-Tab>"] = actions.close,
          -- ["<S-Tab>"] = actions.toggle_selection + actions.move_selection_better,
          ["<C-q>"] = actions.send_to_qflist + actions.open_qflist,
          ["<M-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
          ["<C-l>"] = actions.complete_tag,
          ["<C-h>"] = actions.which_key, -- keys from pressing <C-h>
          -- ["<esc>"] = actions.close,
        },
        n = {
          ["<esc>"] = actions.close,
          ["<CR>"] = actions.select_default,
          ["<C-x>"] = actions.select_horizontal,
          ["<C-v>"] = actions.select_vertical,
          ["<C-t>"] = actions.select_tab,
          ["<C-b>"] = actions.results_scrolling_up,
          ["<C-f>"] = actions.results_scrolling_down,
          ["<Tab>"] = actions.close,
          ["<S-Tab>"] = actions.close,
          ["<C-q>"] = actions.send_to_qflist + actions.open_qflist,
          ["<M-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
          ["j"] = actions.move_selection_next,
          ["k"] = actions.move_selection_previous,
          ["H"] = actions.move_to_top,
          ["M"] = actions.move_to_middle,
          ["L"] = actions.move_to_bottom,
          ["q"] = actions.close,
          ["dd"] = actions.delete_buffer,
          ["s"] = actions.select_horizontal,
          ["v"] = actions.select_vertical,
          ["t"] = actions.select_tab,
          ["<Down>"] = actions.move_selection_next,
          ["<Up>"] = actions.move_selection_previous,
          ["gg"] = actions.move_to_top,
          ["G"] = actions.move_to_bottom,
          ["<C-u>"] = actions.preview_scrolling_up,
          ["<C-d>"] = actions.preview_scrolling_down,
          ["<PageUp>"] = actions.results_scrolling_up,
          ["<PageDown>"] = actions.results_scrolling_down,
          ["?"] = actions.which_key,
        },
      },
    },
    pickers = {
      current_buffer_fuzzy_find = {
        theme = "dropdown",
        previewer = true,
        borderchars = border,
      },
      quickfix = {
        theme = "dropdown",
        previewer = true,
        borderchars = border,
      },
      oldfiles = {
        theme = "dropdown",
        previewer = true,
        borderchars = border,
      },
      live_grep = {
        theme = "dropdown",
        borderchars = border,
      },
      grep_string = {
        theme = "dropdown",
        borderchars = border,
      },
      find_files = {
        theme = "dropdown",
        previewer = true,
        borderchars = border,
      },
      buffers = {
        theme = "dropdown",
        previewer = false,
        borderchars = border,
      },
      planets = {
        show_pluto = true,
        show_moon = true,
      },
      lsp_references = {
        borderchars = border,
        theme = "dropdown",
      },
      lsp_definitions = {
        borderchars = border,
        theme = "dropdown",
      },
      lsp_declarations = {
        borderchars = border,
        theme = "dropdown",
      },
      lsp_implementations = {
        borderchars = border,
        theme = "dropdown",
      },
      git_branches = {
        borderchars = border,
        theme = "dropdown",
        previewer = true,
      },
    },
    extensions = {
      workspaces = {
        theme = "dropdown",
        previewer = true,
      },
    },
  })

  local keymap = vim.keymap.set
  keymap("n", "<Leader>f", "<Cmd>Telescope find_files<CR>", { desc = "Find Files" })
  keymap("n", "<Leader>F", "<Cmd>Telescope live_grep<CR>", { desc = "Live Grep" })
  keymap("n", "<Leader>r", "<Cmd>Telescope oldfiles<CR>", { desc = "Oldfiles" })
  keymap("n", "<Leader>bb", "<Cmd>Telescope buffers<CR>", { desc = "Buffers" })
end)
