vim.loader.enable()
vim.cmd.colorscheme("catppuccin-mocha")

require("rj.extras.last-place")
require("rj.extras.big-file")
require("rj.extras.dashboard")
require("rj.options")
require("rj.keymaps")
require("rj.autocommands")
require("rj.mini-deps")
require("rj.plugins")
require("rj.lsp")
